Linux AppImage Documentation
owncloud/docs-client-desktop pull request #245
Opened 2022-07-18 13:22 UTC by mmattel

Fixes: https://github.com/owncloud/docs-client-desktop/issues/206 ([Linux AppImage] Document installation and use of AppImages)

**ATM WIP**
* **Need more info** on some topics, see referenced issue
* More updates on installing necessary
* Removing page needs an update too

Language review welcomed

The current build is visible on staging

Backport to 2.10 and 2.9

@michaelstingl @TheOneRing @michl19 @jnweiger fyi

2022-07-18 14:27 UTC, phil-davis commented on modules/ROOT/pages/installing.adoc
> +:description: The Desktop Client enables users to access and sync files and folders form their ownCloud, work on remote files right from the desktop as if they were stored on their computer – because
```suggestion
:description: The Desktop Client enables users to access and sync files and folders from their ownCloud, work on remote files right from the desktop as if they were stored on their computer – because they are. Continuous synchronization to and from the ownCloud server provides ease of use combined with comprehensive access control.
```

2022-07-18 14:27 UTC, phil-davis commented on modules/ROOT/pages/installing.adoc
> +You can download the latest version of the ownCloud Desktop Synchronization Client from the {desktop-clients-url}[Desktop Client Download] page. There are clients for _Linux_, _macOS_, and _Microsoft
```suggestion
You can download the latest version of the ownCloud Desktop Client from the {desktop-clients-url}[Desktop Client Download] page. There are clients for _Linux_, _macOS_, and _Microsoft Windows_ available. When using Linux, you can also use Appimage.
```

2022-07-18 14:27 UTC, phil-davis commented on modules/ROOT/pages/installing.adoc
> +Starting with Desktop version 2.9, an {appimage-wikipedia-url}[AppImage] build of the ownCloud Desktop Sync Client is available to support more Linux platforms. You can download the AppImage right at
```suggestion
Starting with Desktop version 2.9, an {appimage-wikipedia-url}[AppImage] build of the ownCloud Desktop Client is available to support more Linux platforms. You can download the AppImage right at the {desktop-clients-url}[Linux section of the Download Desktop App] page.
```

2022-07-18 14:27 UTC, phil-davis commented on modules/ROOT/pages/installing.adoc
> +AppImage is a different way to install Linux applications - not several files (packages) in several places but one file (ending .AppImage) containing the application and all necessary dependency and
```suggestion
AppImage is a different way to install Linux applications - not several files (packages) in several places but one file (ending with .AppImage) containing the application and all necessary dependencies and libraries. There is only a single application AppImage which runs on all (modern) Linux platforms.
```

2022-07-18 14:27 UTC, phil-davis commented on modules/ROOT/pages/installing.adoc
> +* For Ubuntu 22.04 or Debian 11, you need installing `libfuse2` as prerequisite. For details see
```suggestion
* For Ubuntu 22.04 or Debian 11, you need to install `libfuse2` as prerequisite. For details see
```

2022-07-19 07:22 UTC, EParzefall approved these changes

2022-07-19 07:22 UTC, EParzefall commented on modules/ROOT/pages/installing.adoc
> +Linux users must follow the instructions on the {desktop-clients-url}[download] page to add the appropriate repository for their Linux distribution, install the signing key, and use their package man
```suggestion
Linux users must follow the instructions on the {desktop-clients-url}[download] page to add the appropriate repository for their Linux distribution, install the signing key and use their package managers to install the desktop sync client. Linux users will also update their sync clients via package manager. The client will display a notification when an update is available.
```

2022-07-19 07:22 UTC, EParzefall commented on modules/ROOT/pages/installing.adoc
> +* CentOS 7 is currently not supported
```suggestion
* CentOS 7 is currently not supported.
```

2022-07-19 07:22 UTC, EParzefall commented on modules/ROOT/pages/installing.adoc
> +issue with `libfuse` on Ubuntu >=22.04 or Debian 11 {libfuse2-url}[Setting up FUSE 2.x alongside of FUSE 3.x on recent Ubuntu (>=22.04), Debian and their derivatives]
```suggestion
issue with `libfuse` on Ubuntu >=22.04 or Debian 11 {libfuse2-url}[Setting up FUSE 2.x alongside of FUSE 3.x on recent Ubuntu (>=22.04), Debian and their derivatives].
```

2022-07-19 07:22 UTC, EParzefall commented on modules/ROOT/pages/installing.adoc
> +* Install `libfuse2`
```suggestion
* Install `libfuse2`:
```

2022-07-19 07:22 UTC, EParzefall commented on modules/ROOT/pages/installing.adoc
> +The example below uses the terminal but you also can use the GUI, for details see {install-appimage-url}[How to run an AppImage].
```suggestion
The example below uses the terminal but you can also use the GUI. For details see {install-appimage-url}[How to run an AppImage].
```

2022-07-19 07:35 UTC, phil-davis reviewed
Hmmm - I'm not sure what to do in some places. Here are few suggestions and thoughts. I am very happy for someone else to decide what this thing is named in what context.

2022-07-19 07:35 UTC, phil-davis commented on modules/ROOT/pages/installing.adoc
> +Starting with Desktop version 2.9, an {appimage-wikipedia-url}[AppImage] build of the ownCloud Desktop Client is available to support more Linux platforms. You can download the AppImage right at the
```suggestion
Starting with Desktop Client version 2.9, an {appimage-wikipedia-url}[AppImage] build of the ownCloud Desktop Client is available to support more Linux platforms. You can download the AppImage right at the {desktop-clients-url}[Linux section of the Download Desktop Client] page.
```

2022-07-19 07:35 UTC, phil-davis commented on modules/ROOT/partials/nav.adoc
> +* xref:navigating.adoc[Using the Client]
These headings don't have "Desktop". I see that lots of the headings just mention "the Client". I'll leave it to someone else to decide what is the consistent thing to do.

2022-07-19 08:06 UTC, TheOneRing commented on modules/ROOT/pages/installing.adoc
> +* There is no automatic updating. Any update is like installing the AppImage.
Thats not longer the case for 3.0

2022-07-19 08:07 UTC, TheOneRing commented on modules/ROOT/pages/installing.adoc
> +mkdir -p ~/Applications
Any reason for this 'Mac'ism

2022-07-19 13:03 UTC, mmattel commented on modules/ROOT/pages/installing.adoc
> +mkdir -p ~/Applications
This is standard linux writing

2022-07-19 17:06 UTC, TheOneRing commented on modules/ROOT/pages/installing.adoc
> +mkdir -p ~/Applications
I mean the Applications dir

2022-07-19 17:06 UTC, TheOneRing commented
@fmoc can you have a look?

2022-07-19 18:50 UTC, fmoc commented on modules/ROOT/pages/installing.adoc
> +mkdir -p ~/Applications
AppImageLauncher (and some other tools) use this directory by default.

2022-07-20 08:34 UTC, fmoc commented on modules/ROOT/pages/installing.adoc
> +* AppImages do not start automatically. You have to configure your desktop to automatically start the Desktop Client App when logging in. For GNOME, search for _startup applications_ in the desktop m
Note for 3.0: the AppImage will set up the autostart correctly again. This limitation really just affects 2.10.

2022-07-20 09:02 UTC, mmattel commented on modules/ROOT/pages/installing.adoc
> +:libfuse2-url: https://docs.appimage.org/user-guide/troubleshooting/fuse.html#setting-up-fuse-2-x-alongside-of-fuse-3-x-on-recent-ubuntu-22-04-debian-and-their-derivatives
This is not an issue, because when an anchor gets invalid you automatically get on the top of the page.

2022-07-20 09:04 UTC, mmattel commented on modules/ROOT/pages/installing.adoc
> +* AppImages do not start automatically. You have to configure your desktop to automatically start the Desktop Client App when logging in. For GNOME, search for _startup applications_ in the desktop m
As written above, this is the documentation for next which will be backported to 2.10 and 2.9. We will review when 3.0 is out. Standard doc process.

2022-07-21 11:48 UTC, mmattel commented on modules/ROOT/partials/nav.adoc
> +* xref:navigating.adoc[Using the Client]
All namings have now been harmonized to `Desktop App` all over in this repo to be inline with the homepage.

2022-07-21 11:52 UTC, mmattel commented
@fmoc the PR is now ready for your review, you can find the actual build on staging.

@EParzefall @phil-davis pls have a language re-review. The only file necessary is installing.adoc file. The others are only about harmonizing the name.

2022-07-21 12:03 UTC, mmattel commented
Will do an squash before merging...

2022-07-21 12:15 UTC, phil-davis commented on modules/ROOT/pages/installing.adoc
> +* Independent if installing the Desktop App natively or as AppImage, you can add command line parameters when starting up post installation. One parameter to mention is the option `-s`. This option f
```suggestion
* Independent of installing the Desktop App natively or as an AppImage, you can add command line parameters when starting up post installation. One parameter to mention is the option `-s`. This option forces the settings page to be shown on startup. While not necessary on general usage, it can be helpful if systray icons are not available in your desktop system.
```

2022-07-21 12:15 UTC, phil-davis commented on modules/ROOT/pages/installing.adoc
> +Starting with Desktop App version 2.9, an {appimage-wikipedia-url}[AppImage] build of the ownCloud Desktop App is available to support more Linux platforms. You can download the AppImage right at the
```suggestion
Starting with Desktop App version 2.9, an {appimage-wikipedia-url}[AppImage] build of the ownCloud Desktop App is available to support more Linux platforms. You can download the AppImage at the {desktop-clients-url}[Linux section of the Download Desktop App] page.
```

2022-07-21 12:15 UTC, phil-davis commented on modules/ROOT/pages/installing.adoc
> +AppImage is an alternative way to use Linux applications -- instead of having multiple files respectively packages in several places, the entire application is contained in a single file ending with
```suggestion
AppImage is an alternative way to use Linux applications -- instead of having multiple files in several places making up a package, the entire application is contained in a single file ending with an `.AppImage` suffix, including all necessary dependencies and libraries. ownCloud provides a single AppImage which runs on all (modern) Linux platforms.
```

2022-07-21 12:15 UTC, phil-davis commented on modules/ROOT/pages/installing.adoc
> +* The file browser integration, which means overlay icons and the context menu is not included in the AppImage. You need to install file browser extension packages manually.
```suggestion
* The file browser integration, which means overlay icons and the context menu, is not included in the AppImage. You need to install file browser extension packages manually.
```

2022-07-21 12:15 UTC, phil-davis commented on modules/ROOT/pages/installing.adoc
> +* AppImages do not start automatically. You have to configure your desktop to automatically start the Desktop App App when logging in.
```suggestion
* AppImages do not start automatically. You have to configure your desktop to automatically start the Desktop App when logging in.
```

2022-07-21 12:15 UTC, phil-davis commented on modules/ROOT/pages/installing.adoc
> +** As alternative, use the {appimagelauncher-url}[AppImageLauncher] App which also helps managing AppImages.
```suggestion
** As an alternative, use the {appimagelauncher-url}[AppImageLauncher] App which also helps managing AppImages.
```

2022-07-21 12:15 UTC, phil-davis commented on modules/ROOT/pages/installing.adoc
> +See the {install-appimagelauncher-url}[Install AppImageLauncher] wiki for details installing it. The AppImageLauncher does not need to be started. It hooks in when you start and AppImage. There are d
```suggestion
See the {install-appimagelauncher-url}[Install AppImageLauncher] wiki for details about installing it. The AppImageLauncher does not need to be started. It hooks in when you start an AppImage. There are different responses when starting an AppImage:
```

2022-07-21 12:15 UTC, phil-davis commented on modules/ROOT/pages/installing.adoc
> +When you open an AppImage file via your file browser you have not opened before like double click on it:
I am not quite sure what this exactly is meant to say. Maybe?
```suggestion
When you open an AppImage file via your file browser that you have not opened before then double click on it:
```

2022-07-21 12:15 UTC, phil-davis commented on modules/ROOT/pages/installing.adoc
> +Post first time configuration or when you open the AppImage file via your file browser like double clicking on it:
```suggestion
Post first time configuration or when you open the AppImage file via your file browser, for example by double clicking on it:
```

2022-07-21 12:15 UTC, phil-davis commented on modules/ROOT/pages/installing.adoc
> +* Go to the {desktop-clients-url}[download] page and download the recent AppImage to your home directory into the Applications folder. Replace the URL from the example with the actual URL from the do
```suggestion
* Go to the {desktop-clients-url}[download] page and download the recent AppImage into the Applications folder in your home directory. Replace the URL from the example with the actual URL from the download page.
```

2022-07-21 12:15 UTC, phil-davis commented on modules/ROOT/pages/installing.adoc
> +* Note when you start the AppImage post setting it to be executable, the AppImageLauncher will open if installed.
```suggestion
* Note when you start the AppImage after setting it to be executable, the AppImageLauncher will open if installed.
```

Maybe?

2022-07-21 12:15 UTC, phil-davis commented on modules/ROOT/pages/installing.adoc
> +If you just want to install ownCloud Desktop App on your local system, you can simply launch the `.msi` file and configure it in the wizard that pops up.
```suggestion
If you just want to install the ownCloud Desktop App on your local system, you can simply launch the `.msi` file and configure it in the wizard that pops up.
```

2022-07-21 12:15 UTC, phil-davis commented on modules/ROOT/pages/removing.adoc
> +Follow the procedures of your operating system how to remove the Desktop App binary.
```suggestion
Follow the procedures of your operating system about how to remove the Desktop App binary.
```

2022-07-21 12:15 UTC, phil-davis commented on modules/ROOT/pages/removing.adoc
> +When you remove the Desktop App -- the configuration file remains on your system. If you then decide to install the client again, you won't need to re-enter the connection information.
What is the double `--` ?

2022-07-21 12:19 UTC, mmattel commented on modules/ROOT/pages/removing.adoc
> +When you remove the Desktop App -- the configuration file remains on your system. If you then decide to install the client again, you won't need to re-enter the connection information.
making a long dash
`-` makes a single dash line
`--`makes the long dash line

2022-07-22 08:02 UTC, fmoc requested changes

2022-07-22 08:02 UTC, fmoc commented
The rename to "Desktop App" (which I think is wrong, "Desktop Client" seems more reasonable since the latter term is used within the client itself, too) should really be moved to a separate PR. This caused a lot of changes completely unrelated to the actual purpose of the PR, and cost me quite some time to read through the unrelated changes to make sure I don't miss anything related to AppImage.

2022-07-22 08:20 UTC, mmattel commented on antora.yml
> +title: Desktop App
Technically correct with regards to github , but the homepage referes to Desktop App, therefore the harmonisation.

2022-07-22 08:23 UTC, mmattel commented on modules/ROOT/pages/advanced_usage/command_line_options.adoc
> +Depending on your operating system, you can start the ownCloud Desktop App from the command line by typing `owncloud` or `owncloud.exe`. You may need to change to the directory of the binary first. W
```suggestion
Depending on your operating system and how you have installed the Desktop App, you can start the ownCloud Desktop App from the command line by typing `owncloud`, `owncloud.exe` or by the AppImage file name. You may need to change to the directory of the binary first. When starting `owncloud` manually, you can add options to this command.
```

2022-07-22 08:24 UTC, mmattel commented on modules/ROOT/pages/advanced_usage/command_line_options.adoc
> +Depending on your operating system, you can start the ownCloud Desktop App from the command line by typing `owncloud` or `owncloud.exe`. You may need to change to the directory of the binary first. W
Done

2022-07-22 08:35 UTC, mmattel commented on modules/ROOT/pages/installing.adoc
> +* Go to the {desktop-clients-url}[download] page and download the recent AppImage into the Applications folder in your home directory. Replace the URL from the example with the actual URL from the do
```suggestion
* Go to the {desktop-clients-url}[download] page and download the recent AppImage into the Applications folder in your home directory. Replace the URL from the example with the actual URL from the download page. Note the folder name `Applications` can be any name and helps to collect all AppImages you have on one location. The AppImageLauncher, if used, has this name predefined unless you change it.
```

2022-07-22 08:48 UTC, merged